{% set name = "PyFMI" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: 334ae1d629794487d92ecaba23e2b51226f5320db7267ec764c9dcc6df35fd41

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - fmilib
    - numpy
    - cython
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo >=3.0

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
