{% set name = "PyFMI" %}
{% set version = "2.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: 3ce08f2ac8aa0e6685ca806b9cb98f7fb8bf00f6257842bdda25d859081978f9
  patches:
    # disable numpy.distutils as its deprecated and fails to build
    - no_distutils.patch

build:
  number: 0
  skip: true  # [build_platform != target_platform]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - fmilib
    - numpy
    - cython
    - assimulo >=3.0
  run:
    - python
    - fmilib
    - scipy
    - assimulo >=3.0
    - numpy

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: https://github.com/modelon-community/PyFMI
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
