{% set name = "PyFMI" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: e321ff4ba5932c128a9939f93c9dba8e556feff4a5a7e2d86b7bce90c3356f61
  patches:
    # https://github.com/modelon/PyFMI/issues/12
    - logging.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - fmilib
    - numpy
    - cython
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo >=3.0

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
