context:
  version: "2.21.0"

package:
  name: pyfmi
  version: ${{ version }}

source:
  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-${{ version }}.tar.gz
  sha256: 43c8aa643e741682c5fc37b8c1090e1443634a21aff77b9e8a9a9be82bd6dd4c
  patches:
    # disable numpy.distutils as its deprecated and fails to build
    - no_distutils.patch
    - if: win
      then: static.patch

build:
  number: 0
  skip: ${{ build_platform != target_platform }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - numpy
        - cross-python_${{ target_platform }}
        - cython
  host:
    - python
    - setuptools
    - pip
    - fmilib
    - numpy
    - cython
    - assimulo >=3.0
    - if: win
      then: expat
  run:
    - python
    - fmilib
    - scipy
    - assimulo >=3.0
    - numpy

tests:
  - python:
      imports:
        - pyfmi
        - pyfmi.common
        - pyfmi.common.plotting
        - pyfmi.examples
        - pyfmi.simulation

about:
  homepage: https://github.com/modelon-community/PyFMI
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
